# This is a workflow that is manually triggered. It displays a USER environment variable, a secret PASSKEY, and a Greeting variable

name: Environments and Secrets part 2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: dev

    steps:

      # Display the value of the 'dev' environment variable 'USERNAME'
    - name: username from dev
      run: echo "Here is your username ${{ vars.USERNAME }}"


      # Display the value of the 'dev' secret 'PASSKEY
    - name: passkey from dev
      run: echo "Here is your passkey ${{ secrets.PASSKEY }}"
